spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/test?authSource=admin
      encryption:
        enabled: true
        algorithm: AEAD_AES_256_CBC_HMAC_SHA_512-Deterministic
        keyvault:
          database: encryption
          collection: __keyVault
          provider: local
        master-key: 4681d69d42a880c261590cae1028682425690f32125628697d9d0871fd17fc4fd581d7f13d25d52c9a5420f09873b69f